### ISSUE TITLE
ConcurrentModificationException when using LineAndPointRenderer and calling plot.clear()

### ISSUE THREAD

**Issue by tjohnn** [halfhp/androidplot#115]
* Description of the problem
1. `LineAndPointRenderer.cullPointsCache()` checks if registry contains the current LineAndPointFormatter instance `getPlot().getRegistry().contains(series, LineAndPointFormatter.class)`, the `contains()` implementation here runs a foreach loop on an internal arraylist in `SeriesRegistry`
2. The same arraylist in 1 above is cleared when we call plot.clear()
3. if at some we happen to call 1 & 2 above concurrently, then we get `java.util.ConcurrentModificationException`
* Version(s) of Androidplot being used
`1.5.7`
* A stacktrace if the issue is causing a crash

```
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.androidplot.SeriesRegistry.contains(SeriesRegistry.java:130)
        at com.androidplot.xy.LineAndPointRenderer.cullPointsCache(LineAndPointRenderer.java:125)
        at com.androidplot.xy.LineAndPointRenderer$1.onBeforeDraw(LineAndPointRenderer.java:54)
        at com.androidplot.Plot.notifyListenersBeforeDraw(Plot.java:607)
        at com.androidplot.xy.XYPlot.notifyListenersBeforeDraw(XYPlot.java:333)
        at com.androidplot.Plot.renderOnCanvas(Plot.java:881)
        at com.androidplot.Plot.lambda$startBackgroundRendering$0$Plot(Plot.java:440)
        at com.androidplot.Plot$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:920)
```

**Comment by halfhp** [comment]
For performance reasons, Androidplot does not leverage immutability to avoid concurrency issues.  Instead, an interface is exposed to allow users to synchronize their usage with Androidplot's rendering cycles.  See more [here](https://github.com/halfhp/androidplot/blob/master/docs/dynamicdata.md).  In your case it's likely simpler to just synchronize your two calls externally.
